#pragma once

#include "targetver.h"

#include <stdio.h>
#include <tchar.h>


#define MAX_OBJECTS_CHARATER_COUNT 10
#define MAX_OBJECTS_BUILDING_COUNT 10
#define MAX_OBJECTS_BULLET_COUNT 10
#define MAX_OBJECTS_ARROW_COUNT 10
#define MAX_OBJECTS 500
#define OBJECT_CHARACTER 1
#define OBJECT_BUILDING 2
#define OBJECT_BULLET 3
#define OBJECT_ARROW 4

#define BACKGOURND 0.99

#define BULDING 0.1
#define CHARACTER 0.2
#define BULLET 0.3
#define ARROW 0.3

#define TEAM_1 1
#define TEAM_2 2

/*
 text font
 GLUT_STROKE_ROMAN
 GLUT_STROKE_MONO_ROMAN
 GLUT_BITMAP_9_BY_15   
 GLUT_BITMAP_8_BY_13
 GLUT_BITMAP_TIMES_ROMAN_10
 GLUT_BITMAP_TIMES_ROMAN_24
 GLUT_BITMAP_HELVETICA_10
 GLUT_BITMAP_HELVETICA_12
 GLUT_BITMAP_HELVETICA_18
*/